name: Build linux-arm64 artifacts
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup depot tools
        run: |
               git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
               export PATH="$PATH:`pwd`/depot_tools"

      - name: Sync 
        run: |
               cd engine
               gclient sync
               cd src/flutter
               git remote add upstream git@github.com:flutter/engine.git
               cd ..

      - name: Install dependencies
        run: |
              sudo ./build/install-build-deps-android.sh
              sudo ./build/install-build-deps.sh
              sudo ./flutter/build/install-build-deps-linux-desktop.sh



