name: Build linux-arm64 artifacts
on: [push]
jobs:
  build-arm64-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1
      - name: Sync
        run: |
               cd engine
               gclient sync
               cd src/flutter
               git remote add upstream git@github.com:flutter/engine.git
               cd ..

      - name: Install dependencies
        run: |
              sudo ./build/install-build-deps-android.sh
              sudo ./build/install-build-deps.sh
              sudo ./flutter/build/install-build-deps-linux-desktop.sh

      - name: Build artifacts
        run: |
               set -ex
               cd ~/dev/engine/src/flutter
               git fetch upstream
               git rebase upstream/main
               gclient sync
               cd ..

               flutter/tools/gn --unoptimized --runtime-mode=debug
               flutter/tools/gn --android --unoptimized --runtime-mode=debug
               flutter/tools/gn --android --runtime-mode=profile
               flutter/tools/gn --android --runtime-mode=release

               cd out
               find . -mindepth 1 -maxdepth 1 -type d | xargs -n 1 sh -c 'ninja -C $0 || exit 255'
